[package]
name = "tardigrade"
version = "0.1.0"
edition = "2021"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["orchestration", "workflow", "business process"]
categories = ["asynchronous", "wasm"]
description = "Client bindings for Tardigrade workflows"
repository = "https://github.com/slowli/tardigrade"

[dependencies]
chrono = "0.4.19"
futures = "0.3.21"
once_cell = "1.12.0"
pin-project-lite = "0.2.9"
serde = "1"
serde_json = { version = "1", optional = true }
slab = "0.4.6"

tardigrade-shared = { version = "0.1.0", path = "crates/shared" }
tardigrade-derive = { version = "0.1.0", path = "crates/derive", optional = true }

[dev-dependencies]
assert_matches = "1.5.0"
async-io = "1.7.0"
rand = "0.8.5"
version-sync = "0.9.4"

[features]
default = ["serde_json"]
derive = ["tardigrade-derive"]

[[test]]
name = "integration"
path = "tests/integration/main.rs"
required-features = ["derive"]

[profile.wasm]
inherits = "release"
panic = "abort"
codegen-units = 1
opt-level = "z" # Optimize for size, rather than speed
lto = true

[workspace]
members = [
  ".",
  "crates/shared",
  "crates/derive",
  "crates/rt",
  "e2e-tests/basic",
]
