[package]
name = "tardigrade-rt"
version = "0.1.0"
edition = "2021"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["orchestration", "workflow", "business process"]
categories = ["asynchronous", "wasm"]
description = "Runtime for Tardigrade workflows"
repository = "https://github.com/slowli/tardigrade"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.57"
base64 = "0.13.0"
chrono = { version = "0.4.22", features = ["serde"] }
flate2 = "1.0.24" # TODO: make optional? (+ expose workflow memory)
futures = "0.3.21"
leb128 = "0.2.5"
once_cell = "1.13.0"
pin-project-lite = "0.2.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
wasmtime = "1.0.1"

## Standalone optional dependencies
# Implements the scheduler trait based on `async-io` / `async-std` runtime.
async-io = { version = "1.7.0", optional = true }
# Enables tracing during workflow execution.
tracing = "0.1.37"

tardigrade = { version = "0.1.0", path = "../.." }

[dependencies.tracing-tunnel]
version = "0.1.0"
git = "https://github.com/slowli/tracing-toolbox.git"
rev = "502655fa03d9bcd9f7721b05baba63b550b3d599"
features = ["receiver"]

[dev-dependencies]
assert_matches = "1.5.0"
async-std = "1.12.0"
mimicry = "0.1.0"
version-sync = "0.9.4"
