[package]
name = "tardigrade-rt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
chrono = "0.4.19"
leb128 = "0.2.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasmtime = "0.37.0"

tardigrade-shared = { version = "0.1.0", path = "../shared" }
tardigrade = { version = "0.1.0", path = "../.." }
# FIXME: is this dep really necessary? (maybe move interface defs to the shared crate)
