[package]
name = "tardigrade-rt"
version = "0.1.0"
edition = "2021"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["orchestration", "workflow", "business process"]
categories = ["asynchronous", "wasm"]
description = "Runtime for Tardigrade workflows"
repository = "https://github.com/slowli/tardigrade"

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
chrono = { version = "0.4.22", features = ["serde"] }
flate2 = "1.0.24" # TODO: make optional? (+ expose workflow memory)
leb128 = "0.2.5"
once_cell = "1.13.0"
serde = { version = "1", features = ["derive"] }
wasmtime = "1.0.1"

futures = { version = "0.3.21", optional = true }
pin-project-lite = { version = "0.2.9", optional = true }

## Standalone optional dependencies
# Implements the scheduler trait based on `async-io` / `async-std` runtime.
async-io = { version = "1.7.0", optional = true }
# Enables logging during workflow execution.
log = { version = "0.4.17", optional = true }

tardigrade-shared = { version = "0.1.0", path = "../shared" }
tardigrade = { version = "0.1.0", path = "../.." }

[dev-dependencies]
assert_matches = "1.5.0"
async-std = "1.12.0"
mimicry = "0.1.0"
serde_json = "1.0"
version-sync = "0.9.4"

[features]
default = []
# Exposes async handles for workflows.
async = ["futures", "pin-project-lite"]
