[package]
name = "tardigrade-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
