name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  msrv: 1.65.0
  nightly: nightly-2022-09-22
  binaryen: version_110

jobs:
  build-msrv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-msrv-cargo-build-target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.msrv }}
          override: true
          target: wasm32-unknown-unknown

      - name: Install wasm-opt
        run: |
          wget -q -O binaryen.tar.gz "https://github.com/WebAssembly/binaryen/releases/download/$binaryen/binaryen-$binaryen-x86_64-linux.tar.gz" && \
          tar xf binaryen.tar.gz && \
          sudo install "binaryen-$binaryen/bin/wasm-opt" /usr/local/bin

      # Build the E2E crate first to speed up its testing.
      - name: Build E2E test crate
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p tardigrade-pizza --lib --target wasm32-unknown-unknown --profile wasm

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features --all-targets
      - name: Run doc tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features --doc

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Install wasm-opt
        run: |
          wget -q -O binaryen.tar.gz "https://github.com/WebAssembly/binaryen/releases/download/$binaryen/binaryen-$binaryen-x86_64-linux.tar.gz" && \
          tar xf binaryen.tar.gz && \
          sudo install "binaryen-$binaryen/bin/wasm-opt" /usr/local/bin

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Clippy: all features"
          args: --workspace --all-features --all-targets -- -D warnings
      - name: Clippy (WASM client bindings)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Clippy: WASM client bindings"
          args: -p tardigrade --lib --target wasm32-unknown-unknown -- -D warnings
      - name: Clippy (runtime, no features)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Clippy: runtime, no features"
          args: -p tardigrade-rt --lib --no-default-features -- -D warnings

      # Build the E2E crate first to speed up its testing.
      - name: Build E2E test crate
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p tardigrade-pizza --lib --target wasm32-unknown-unknown --profile wasm

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features --all-targets
      - name: Run doc tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features --doc

  document:
    if: github.event_name == 'push'
    needs:
      - build
      - build-msrv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-document-target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.nightly }}
          profile: minimal
          override: true

      - name: Build docs
        run: |
          cargo clean --doc && \
          cargo rustdoc -p tardigrade-shared --all-features -- --cfg docsrs && \
          cargo rustdoc -p tardigrade --all-features -- --cfg docsrs && \
          cargo rustdoc -p tardigrade-rt --all-features -- --cfg docsrs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/doc
          single-commit: true
